name: Deploy Progressive Web App (PWA)

on:
  push:
    branches:
      - main

jobs:
  deploy-pwa:
    name: Deploy PWA
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./